services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "4005:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared_network

  iam-service:
    build:
      context: .
      dockerfile: iam-service/Dockerfile
    expose:
      - "3001"
    env_file:
      - ./.env
    environment:
      - APP_PORT=3001
      - GRPC_PORT=50051
    volumes:
      - /opt/motrava/config/service-account.json:/app/service-account.json:ro
    networks:
      - shared_network

  core-service:
    build:
      context: .
      dockerfile: core-service/Dockerfile
    expose:
      - "3002"
    env_file:
      - ./.env
    environment:
      - APP_PORT=3002
      - IAM_SERVICE_ADDRESS=iam-service:50051
    volumes:
      - /opt/motrava/config/service-account.json:/app/service-account.json:ro
    depends_on:
      - iam-service
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
